---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.1
  #- name: centos-6.6
  #- name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[nginx::default]
    attributes:
